url: https://silviogiancola.github.io
baseurl: /SoccerNet/

# Site settings
title: SoccerNet
email: silvio.giancola@kaust.edu.sa
description: "SoccerNet is a scalable dataset for action spotting in soccer videos. 
It is composed of 500 complete soccer games from six main European leagues, covering three seasons from 2014 to 2017 and a total duration of 764 hours."


# Team names, titles and social links
people:
  - name: Silvio Giancola
    pic: SilvioGiancola
    social:
      - title: ai ai-google-scholar
        url: https://scholar.google.com/citations?user=2kq5Zl0AAAAJ&hl=en #
      - title: fab fa-github
        url: https://github.com/silviogiancola
      - title: fa fa-graduation-cap
        url: https://silviogiancola.github.io/

  - name: Mohieddine Amine
    pic: MohieddineAmine

  - name: Tarek Dghaily
    pic: TarekDghaily


  - name: Bernard Ghanem
    pic: BernardGhanem
    # position: Lead Developer
    social:
      - title: ai ai-google-scholar
        url: https://scholar.google.com/citations?user=rVsGTeEAAAAJ&hl=en #
      - title: fa fa-graduation-cap
        url: http://www.bernardghanem.com/ #



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: fas fa-envelope 
    url: mailto:silvio.giancola@kaust.edu.sa
  - title: fab fa-github
    url: http://github.com/silviogiancola

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty




collections:
    sections:
      output: true
      permalink: /:collection/:name
    publications:
      output: true
      permalink: /:collection/:name


# enformed_token: 7pq7zv8s # silvio.giancola@gmail.com
enformed_token: gzjcu9k0 # silvio.giancola@kaust.edu.sa

# Google Analytics
google_analytics: UA-99166333-3



